# Generated by Django 4.0 on 2021-12-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('auth', models.CharField(max_length=50)),
                ('store', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
